# Generated by Django 6.0.3 on 2026-03-22 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee_for',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='fee_transaction',
                to='transactions.transaction',
            ),
        ),
    ]
