# Generated by Django 6.0.3 on 2026-03-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_add_is_fee_fee_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='fee_for',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_fee',
        ),
    ]
