# Generated by Django 6.0.3 on 2026-03-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_is_active_archived_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_ac_user_id_6d63db_idx',
            old_name='accounts_ac_user_id_3f14ee_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_ac_type_cd282c_idx',
            old_name='accounts_ac_type_93b7c1_idx',
        ),
    ]
